// @/prompts
export const prompts = [
  {
    id: "section1",
    title: "",
    items: [
      { id: "q1", text: "Commented without substance on short-form videos?" },
      { id: "q2", text: "Reposted any video that seems somewhat relatable?" },
      { id: "q3", text: "Reposted a video of someone that is intellectually/physically/attractively inferior performing a relatable action?" },
      { id: "q4", text: "Drank matcha?" },
      { id: "q5", text: "Drank a matcha with oat milk despite not being lactose intolerant?" },
      { id: "q6", text: "Drank bad matcha and talked about how they're not using ceremonial grade?" },
      { id: "q7", text: "Talked about the matcha shortage in 2025?" },
      { id: "q8", text: "Talked about being into fashion, but your daily is UNIQLO essentials and baggy jeans off MUSINSA?" },
      { id: "q9", text: "Owned a pair of IONGAF chonies?" },
      { id: "q10", text: "Owned any article of clothing from Yuremane?" },
      { id: "q11", text: "Owned any article of clothing from ktwo?" },
      { id: "q12", text: "Owned any article of clothing from an Instagram brand?" },
      { id: "q13", text: "Owned a Smiski, Miffy, or Labubu with intention of attracting those who appreciate the culture?" },
      { id: "q14", text: "Posted a photo on your story just so your crush would see it?" },
      { id: "q15", text: "Posted a photo of a matcha latte on your story?" },
      { id: "q16", text: "Posted a random photo with a niche artist as the background music?" },
      { id: "q17", text: "Deleted posts where you had genuine memories but looked bad?" },
      { id: "q18", text: "Cropped out your friend in a post because you looked good?" },
      { id: "q19", text: "Had a finsta?" },
      { id: "q20", text: "Purged followers off of your main account to maintain mysteriousness?" },
      { id: "q21", text: "Deactivated your account without good reason just to maintain mysteriousness?" },
      { id: "q22", text: "Spent more than 10 minutes picking a 15-second snippet for your Instagram story?" },
      { id: "q23", text: "Spent more than 10 minutes adding overloads of filters to achieve a Y2K effect on your photos?" },
      { id: "q24", text: "Made a Day-In-My-Life video?" },
      { id: "q25", text: "Made a Get-Ready-With-Me video?" },
      { id: "q26", text: "Made a fit check video?" },
      { id: "q27", text: "Made a thirst trap?" },
      { id: "q28", text: "Made a TikTok career off of thirst-trapping?" },
      { id: "q29", text: "Made a brand deal video that seemed fairly obvious that you are not actually advertising the product?" },
      { id: "q30", text: "Made a story time video?" },
      { id: "q31", text: "Made a TikTok that puts down others?" },
      { id: "q32", text: "Said 'niche for niche'?" },
      { id: "q33", text: "Participated in comparing two artists that have no relation to each other?" },
      { id: "q34", text: "Participated in commenting unusually niche jokes and not caring to explain them in comment sections?" },
      { id: "q35", text: "Participated in 'Jane Remover/2hollis blaccent cafe'?" },
      { id: "q36", text: "Put down anyone for listening to a certain type of music?" },
      { id: "q37", text: "Gatekept anything from an individual without good reason?" },
      { id: "q38", text: "Commented on someone's looks behind their back?" },
      { id: "q39", text: "Owned a bomber account just to argue with strangers?" },
      { id: "q40", text: "Donated to a streamer for them to say your name?" },
    ],
  },
]
