// @/prompts
export const prompts = [
  {
    id: "section1",
    title: "",
    items: [
      { id: "q1", text: "Commented without substance on short-form videos?" },
      { id: "q2", text: "Reposted any video that seems somewhat relatable?" },
      { id: "q3", text: "Reposted a video of someone that is intellectually/physically/attractively inferior performing a relatable action?" },
      { id: "q4", text: "Drank matcha?" },
      { id: "q5", text: "Drank a matcha with oat milk despite not being lactose intolerant?" },
      { id: "q6", text: "Drank bad matcha and talked about how they're not using ceremonial grade?" },
      { id: "q7", text: "Talked about the matcha shortage in 2025?" },
      { id: "q8", text: "Talked about being into fashion, but your daily is UNIQLO essentials and baggy jeans off MUSINSA?" },
      { id: "q9", text: "Owned a pair of IONGAF chonies?" },
      { id: "q10", text: "Owned any article of clothing from Yuremane?" },
      { id: "q11", text: "Owned any article of clothing from ktwo?" },
      { id: "q12", text: "Owned any article of clothing from an Instagram brand?" },
      { id: "q13", text: "Kissed someone below the belt?" },
      { id: "q14", text: "Kissed for more than two hours consecutively?" },
      { id: "q15", text: "Played a game involving stripping?" },
      { id: "q16", text: "Seen or been seen by another person in a sensual context?" },
      { id: "q17", text: "Masturbated?" },
      { id: "q18", text: "Masturbated to a picture or video?" },
      { id: "q19", text: "Masturbated while someone else was in the room?" },
      { id: "q20", text: "Been caught masturbating?" },
      { id: "q21", text: "Owned a Smiski, Miffy, or Labubu with intention of attracting those who appreciate the culture?" },
      { id: "q22", text: "Posted a photo on your story just so your crush would see it?" },
      { id: "q23", text: "Posted a photo of a matcha latte on your story?" },
      { id: "q24", text: "Posted a random photo with a niche artist as the background music?" },
      { id: "q25", text: "Seen or touched another person's breast?" },
      { id: "q26", text: "Had your breast seen or touched by another person?" },
      { id: "q27", text: "Seen or touched another person's genitals?" },
      { id: "q28", text: "Had your genitals seen or touched by another person?" },
      { id: "q29", text: "Sent a sexually explicit text or instant message?" },
      { id: "q30", text: "Sent or received sexually explicit photographs?" },
      { id: "q31", text: "Engaged in sexually explicit activity over video chat?" },
      { id: "q32", text: "Cheated on a significant other during a relationship?" },
      { id: "q33", text: "insta thing" },
      { id: "q34", text: "Deleted posts where you had genuine memories but looked bad?" },
      { id: "q35", text: "Cropped out your friend in a post because you looked good?" },
      { id: "q36", text: "Had a finsta?" },
      { id: "q37", text: "Purged followers off of your main account to maintain mysteriousness?" },
      { id: "q38", text: "Deactivated your account without good reason just to maintain mysteriousness?" },
      { id: "q39", text: "Spent more than 10 minutes picking a 15-second snippet for your Instagram story?" },
      { id: "q40", text: "Spent more than 10 minutes adding overloads of filters to achieve a Y2K effect on your photos?" },
      { id: "q41", text: "Engaged in sexual intercourse while someone else was in the same room?" },
      { id: "q42", text: "Engaged in sexual intercourse with a stranger?" },
      { id: "q43", text: "Had sexual intercourse 3 or more times in one night?" },
      { id: "q44", text: "Had sexual intercourse with 5 or more partners?" },
      { id: "q45", text: "Been photographed or filmed during sexual intercourse by yourself or others?" },
      { id: "q46", text: "Had sexual intercourse while under the influence of alcohol or drugs?" },
      { id: "q47", text: "Had sexual intercourse with someone under the influence of alcohol or drugs?" },
      { id: "q48", text: "Had a STI test due to reasonable suspicion?" },
      { id: "q49", text: "Had a STI?" },
      { id: "q50", text: "Had a pregnancy scare?" },
      { id: "q51", text: "Impregnated someone or been impregnated?" },
      { id: "q52", text: "Paid or been paid for a sexual act?" },
      { id: "q53", text: "Committed an act of voyeurism?" },
      { id: "q54", text: "Committed an act of incest?" },
      { id: "q55", text: "Engaged in bestiality?" },
      { id: "q56", text: "Engaged in a ménage à trois?" },
      { id: "q57", text: "Engaged in an orgy?" },
      { id: "q58", text: "Drank alcohol in a non-religious context?" },
      { id: "q59", text: "Been drunk?" },
      { id: "q60", text: "Faked sobriety to parents or teachers?" },
      { id: "q61", text: "Had severe memory loss due to alcohol?" },
      { id: "q62", text: "Used tobacco?" },
      { id: "q63", text: "Used marijuana?" },
      { id: "q64", text: "Used a drug stronger than marijuana?" },
      { id: "q65", text: "Used methamphetamine, crack cocaine, PCP, horse tranquilizers or heroin?" },
      {
        id: "q66",
        text: "Been sent to the office of a principal, dean or judicial affairs representative for a disciplinary infraction?",
      },
      { id: "q67", text: "Been put on disciplinary probation or suspended?" },
      { id: "q68", text: "Made a Day-In-My-Life video?" },
      { id: "q69", text: "Made a Get-Ready-With-Me video?" },
      { id: "q70", text: "Made a fit check video?" },
      { id: "q71", text: "Made a thirst trap?" },
      { id: "q72", text: "Made a TikTok career off of thirst-trapping?" },
      { id: "q73", text: "Made a brand deal video that seemed fairly obvious that you are not actually advertising the product?" },
      { id: "q74", text: "Made a story time video?" },
      { id: "q75", text: "Made a TikTok that puts down others?" },
      { id: "q76", text: "Been arrested?" },
      { id: "q77", text: "Been convicted of a crime?" },
      { id: "q78", text: "Been convicted of a felony?" },
      { id: "q79", text: "Committed an act of vandalism?" },
      { id: "q80", text: "Had sexual intercourse in a motor vehicle?" },
      { id: "q81", text: "Had sexual intercourse outdoors?" },
      { id: "q82", text: "Had sexual intercourse in three or more positions?" },
      { id: "q83", text: "Had sexual intercourse with a person of the same sex?" },
      { id: "q84", text: "Had sexual intercourse with a virgin?" },
      { id: "q85", text: "Had sexual intercourse without your parents' knowledge?" },
      { id: "q86", text: "Had sexual intercourse without your partner's parents' knowledge?" },
      { id: "q87", text: "Lied to a partner about the number of sexual partners you have had?" },
      { id: "q88", text: "Lied to a partner about having an STI?" },
      { id: "q89", text: "Said 'niche for niche'?" },
      { id: "q90", text: "Participated in comparing two artists that have no relation to each other?" },
      {
        id: "q91",
        text: "Participated in commenting unusually niche jokes and not caring to explain them in comment sections?",
      },
      { id: "q92", text: "Participated in 'Jane Remover/2hollis blaccent cafe'?" },
      { id: "q93", text: "" },
      { id: "q94", text: "Had sexual intercourse with a partner with a 7 or more year age difference?" },
      { id: "q95", text: "Had a partner take off a condom during intercourse without your knowledge or consent?" },
      { id: "q96", text: "Put down anyone for listening to a certain type of music?" },
      { id: "q97", text: "Gatekept anything from an individual without good reason?" },
      { id: "q98", text: "Commented on someone's looks behind their back?" },
      { id: "q99", text: "Owned a bomber account just to argue with strangers?" },
      { id: "q100", text: "Donated to a streamer for them to say your name?" },
    ],
  },
]
